// <auto-generated />
using CampusGuideWSG.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CampusGuideWSG.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260920215531_FixedManyToMany")]
    partial class FixedManyToMany
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CampusGuideWSG.Models.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Name" }, "BUILDINGS_NAME_IX")
                        .IsUnique();

                    b.ToTable("buildings", (string)null);
                });

            modelBuilder.Entity("CampusGuideWSG.Models.Entrance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildingId")
                        .HasColumnType("int(11)")
                        .HasColumnName("building_id");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isOpen");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "BuildingId" }, "ENTRANCES_BUILDINGS_FK");

                    b.HasIndex(new[] { "Name" }, "ENTRANCES_NAME_IX")
                        .IsUnique();

                    b.ToTable("entrances", (string)null);
                });

            modelBuilder.Entity("CampusGuideWSG.Models.Moderator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int(11)")
                        .HasColumnName("role_id");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("surname");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "RoleId" }, "MODERATORS_ROLES_FK");

                    b.HasIndex(new[] { "Username" }, "MODERATORS_USERNAME_IX")
                        .IsUnique();

                    b.ToTable("moderators", (string)null);
                });

            modelBuilder.Entity("CampusGuideWSG.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("CampusGuideWSG.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildingId")
                        .HasColumnType("int(11)")
                        .HasColumnName("building_id");

                    b.Property<int>("Number")
                        .HasColumnType("int(3)")
                        .HasColumnName("number");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "BuildingId" }, "ROOMS_BUILDINGS_FK");

                    b.HasIndex(new[] { "Number" }, "ROOMS_NUMBER_IX")
                        .IsUnique();

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("moderators_buildings", b =>
                {
                    b.Property<int>("moderator_id")
                        .HasColumnType("int(11)");

                    b.Property<int>("building_id")
                        .HasColumnType("int(11)");

                    b.HasKey("moderator_id", "building_id");

                    b.HasIndex("building_id");

                    b.HasIndex("moderator_id", "building_id")
                        .IsUnique()
                        .HasDatabaseName("MODERATORS_BUILDINGS_IX");

                    b.ToTable("moderators_buildings", (string)null);
                });

            modelBuilder.Entity("CampusGuideWSG.Models.Entrance", b =>
                {
                    b.HasOne("CampusGuideWSG.Models.Building", "Building")
                        .WithMany("Entrances")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("ENTRANCES_BUILDINGS_FK");

                    b.Navigation("Building");
                });

            modelBuilder.Entity("CampusGuideWSG.Models.Moderator", b =>
                {
                    b.HasOne("CampusGuideWSG.Models.Role", "Role")
                        .WithMany("Moderators")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("MODERATORS_ROLES_FK");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CampusGuideWSG.Models.Room", b =>
                {
                    b.HasOne("CampusGuideWSG.Models.Building", "Building")
                        .WithMany("Rooms")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("ROOMS_BUILDINGS_FK");

                    b.Navigation("Building");
                });

            modelBuilder.Entity("moderators_buildings", b =>
                {
                    b.HasOne("CampusGuideWSG.Models.Building", null)
                        .WithMany()
                        .HasForeignKey("building_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("MODERATORS_BUILDINGS_BUILDINGS_FK");

                    b.HasOne("CampusGuideWSG.Models.Moderator", null)
                        .WithMany()
                        .HasForeignKey("moderator_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("MODERATORS_BUILDINGS_MODERATORS_FK");
                });

            modelBuilder.Entity("CampusGuideWSG.Models.Building", b =>
                {
                    b.Navigation("Entrances");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("CampusGuideWSG.Models.Role", b =>
                {
                    b.Navigation("Moderators");
                });
#pragma warning restore 612, 618
        }
    }
}
